title: "Florius’ Blog"
email: j@florius.com.ar
description: >-
  Joaquin "Flroius" Azcarate’s personal blog
baseurl: ""
url: "https://blog.florius.com.ar"

# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

show_social_icons: true
animated: true
show_related_posts: true
enable_anchorjs: true
permalink:    pretty
paginate:     5
date_format: "%b %-d, %Y"

google_tag_manager: G-689SEV7MTT

# Social
github_username: jazcarate
gitlab_username: jazcarate
linkedin_username: joaquin-azcarate
devto_username: florius

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - ATTRIBUTION.md
  - vendor