title: "Florius’ Blog"
email: j@florius.com.ar
description: >-
  Joaquin 'Florius' Azcarate’s personal blog
baseurl: ""
url: "https://blog.florius.com.ar"

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

twitter:
  username: FloriusWasTaken
author: florius
seo_paginator_message: "%<current>s / %<total>s | "

show_social_icons: true
animated: true
show_related_posts: true
max_related: 3
enable_anchorjs: true
permalink:    pretty
paginate:     3
date_format: "%b %-d, %Y"

google_tag_manager: G-689SEV7MTT

# Social
github_username: jazcarate
gitlab_username: jazcarate
linkedin_username: joaquin-azcarate
devto_username: florius

assets:
   plugins:
    img: { optim: {}}

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - ATTRIBUTION.md
  - vendor
  - .devcontainer/
  - .vscode/
  - .github